ALTER DATABASE [pagecache5] ADD FILEGROUP [area0]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area1]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area2]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area3]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area4]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area5]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area6]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area7]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area8]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [area9]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [areaa]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [areab]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [areac]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [aread]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [areae]
GO
ALTER DATABASE [pagecache5] ADD FILEGROUP [areaf]
GO
